name: Run unit tests

on:
  push:
    branches:
      - '*'

env:
  DD_CIVISIBILITY_ENABLED: true
  DD_CIVISIBILITY_AGENTLESS_ENABLED: true
  DD_SITE: datad0g.com
  DD_ENV: ci
  DD_SERVICE: ci-test-project
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
  CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
  DD_TRACER_FOLDER: /usr/local/bin
  DD_CIVISIBILITY_FLAKY_RETRY_ENABLED: true

jobs:
  run-tests:
    name: run-unit-tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.5.4' ]
        java: [ '11' ]

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Print env
        shell: bash
        run: |
          env
      - name: Print OS details
        shell: bash
        run: |
          uname -a && cat /etc/*release
      - name: Install datadog libraries
        run: |
          DD_INSTALL_ONLY=true DD_APM_INSTRUMENTATION_ENABLED=host DD_APM_INSTRUMENTATION_LANGUAGES=java bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh)"
      - name: Run unit tests
        run: |
          mvn clean test
