name: Run dd-javac-plugin tests

on:
  push:
    branches:
      - '*'

env:
  DD_CIVISIBILITY_ENABLED: true
  DD_CIVISIBILITY_AGENTLESS_ENABLED: true
  DD_SITE: datad0g.com
  DD_ENV: ci
  DD_SERVICE: ci-test-project
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
  CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
  DD_TRACER_FOLDER: /usr/local/bin

jobs:
  run-tests:
    name: run-unit-tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.5.4' ]
        java: [ '11' ]

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Print env
        shell: bash
        run: |
          env
      - name: download Java tracer
        run: |
          ./load-binary.sh nikita-tkachenko/retry-flaky-tests
      - name: run-unit-tests
        run: |
          MAVEN_OPTS=-javaagent:$DD_TRACER_FOLDER/dd-java-agent.jar mvn clean test
