name: Run auto-instrumented unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  run-tests:
    name: run-unit-tests
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/openjdk11:latest

    strategy:
      matrix:
        maven: [ '3.5.4' ]
        java: [ '11' ]

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@v1.0.1
        with:
          languages: java
          service-name: ciapp-test-nikita
          api-key: ${{ secrets.DD_API_KEY }}
      - name: Run unit tests
        run: |
          mvn clean test
        env:
          DD_CIVISIBILITY_JACOCO_PLUGIN_VERSION: 0.8.11
