name: Run auto-instrumented unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  run-tests:
    name: run-unit-tests
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/openjdk11:latest

    strategy:
      matrix:
        maven: [ '3.5.4' ]
        java: [ '11' ]

    steps:
      - name: Configure Datadog Test Visibility
        uses: nikita-tkachenko-datadog/gha-composite-test@main
        with:
          languages: java
          service-name: ciapp-test-nikita
          api-key: ${{ secrets.DD_API_KEY }}
      - name: Look for tracer
        run: |
          echo 1
          find $GITHUB_WORKSPACE/.datadog -type f
          
          echo 2
          ls -la $GITHUB_WORKSPACE/.datadog

          echo 3 
          find /github/workspace/.datadog/ -type f

          echo 4 
          ls -la /github/workspace/

          echo 5 
          ls -la /github/workspace/.datadog/
          
          echo 6
          ls -la /github/workspace/.datadog/dd-java-agent.jar
          
          echo 7
          java -jar /github/workspace/.datadog/dd-java-agent.jar
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Run unit tests
        run: |
          find /github/workspace/.datadog -type f
          mvn clean test
        env:
          DD_CIVISIBILITY_JACOCO_PLUGIN_VERSION: 0.8.11
      - name: Run containerized action
        id: run-containerized-action
        uses: nikita-tkachenko-datadog/github-container-action@main
        with:
          who-to-greet: Nikita
