name: Run auto-instrumented unit tests

on:
  push:
    branches:
      - '*'

env:
  DD_CIVISIBILITY_INSTRUMENTATION_LANGUAGES: java
  DD_SERVICE: ci-test-project
  DD_API_KEY: ${{ secrets.DD_API_KEY }}

jobs:
  run-tests:
    name: run-unit-tests
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/openjdk11:latest

    strategy:
      matrix:
        maven: [ '3.5.4' ]
        java: [ '11' ]

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Configure Datadog Test Visibility
        uses: nikita-tkachenko-datadog/gha-composite-test@v17
      - name: Run unit tests
        run: |
          mvn clean test
